# Generated by Django 2.1.5 on 2019-01-21 15:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=1)),
                ('nickname', models.CharField(max_length=20)),
                ('avatar', models.URLField()),
                ('avatar_thumb', models.URLField()),
                ('bio', models.CharField(max_length=200)),
                ('open_bio', models.BooleanField(default=True)),
                ('wx_openid', models.CharField(blank=True, max_length=20, null=True)),
                ('wx_nickname', models.CharField(blank=True, max_length=20, null=True)),
                ('wx_avatar', models.URLField(blank=True, null=True)),
                ('last_ip', models.GenericIPAddressField(blank=True, null=True, unpack_ipv4=True)),
                ('join_ip', models.GenericIPAddressField(blank=True, null=True, unpack_ipv4=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
