# Generated by Django 2.1.5 on 2019-01-21 15:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wx_auth', '0001_initial'),
        ('pet', '0002_auto_20190121_2342'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag', models.IntegerField(choices=[(1, 'Yes'), (2, 'No')], default=1)),
                ('read', models.BooleanField(default=False)),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_update_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('create_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_message', to='wx_auth.UserProfile')),
                ('last_update_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_message', to='wx_auth.UserProfile')),
                ('receiver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_messages', to='wx_auth.UserProfile')),
                ('reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='pet.Message')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_messages', to='wx_auth.UserProfile')),
            ],
        ),
        migrations.AlterField(
            model_name='comment',
            name='found',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comment', to='pet.PetFound'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='lost',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comment', to='pet.PetLost'),
        ),
    ]
